### ISSUE TITLE
work on the writes ups for about us page and product page

### ISSUE THREAD

**Issue by BenEmet** [zuri-training/t_c-generator-team71#118]
Get contents for the about us pages and the product pages

**Comment by Chinonye-Ochi** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2608%3A53408
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2608%3A55461
