### ISSUE TITLE
Design the Authenticated Hi-fi of the profile page(Mobile)

### ISSUE THREAD

**Issue by Muminat** [zuri-training/t_c-generator-team71#138]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2109%3A43615

https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2115%3A43682

**Comment by SenseiLey** [comment]
Done
