### ISSUE TITLE
Create the Lo-Fi design of the Sign Up Page

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#14]

**Comment by 0laolu** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Project-71?node-id=1292%3A39337

**Comment by BenEmet** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2461%3A76862
original
