### ISSUE TITLE
Create a Hi-Fi Design for the Sign-Up and Login Pages in Figma

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#28]

**Comment by 0laolu** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Project-71?node-id=610%3A36557

**Comment by 0laolu** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Project-71?node-id=444%3A35448

**Comment by BenEmet** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A57663
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A69496
original
