### ISSUE TITLE
Create a Hi-Fi Design for the Forgot Password and Reset Password Pages in Figma

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#29]

**Comment by 0laolu** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Project-71?node-id=444%3A35596
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Project-71?node-id=444%3A35875

**Comment by BenEmet** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A69403
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A69638
