### ISSUE TITLE
Create an Empathy Map in Figjam

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#3]

**Comment by 0laolu** [comment]
https://www.figma.com/file/jJEux6m23ufOjVtu4M2tBs/Project-71?node-id=82%3A248

**Comment by BenEmet** [comment]
https://www.figma.com/file/jJEux6m23ufOjVtu4M2tBs/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=351%3A833
