### ISSUE TITLE
Create the Lo-Fi Design of the Login Page in Figma

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#31]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Project-71?node-id=1292%3A39464

**Comment by BenEmet** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2461%3A78186
original
