### ISSUE TITLE
Create the Hi-Fi of the About Us Page in Figma

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#38]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Project-71?node-id=1301%3A39763

**Comment by BenEmet** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/For-Further-Edits-Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2487%3A58740

this is the original link
