### ISSUE TITLE
Design the Lo-fi of the mobile view of the Reset Password Page

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#56]

**Comment by Chinonye-Ochi** [comment]
yes boss...

**Comment by Chinonye-Ochi** [comment]
I also did the Lo-fi for the About Us page

**Comment by 0laolu** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2333%3A71935
