### ISSUE TITLE
Design the Hi-fi of mobile view of the Contact Us Page

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#57]

**Comment by 0laolu** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A67709

https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A68498

**Comment by Muniratize** [comment]
Done Boss
