### ISSUE TITLE
Design the Hi-fi of the mobile view of the About Us Page

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#58]

**Comment by Muniratize** [comment]
Okay Noted boss

**Comment by 0laolu** [comment]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A57786
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A59982
