### ISSUE TITLE
Design the mobile view of the How It works section on Landing Page

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#94]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=2356%3A62181

**Comment by Muminat** [comment]
I worked on the how it works together with my co-designers.

**Comment by Muniratize** [comment]
This was interesting to work on

**Comment by Muniratize** [comment]
This was interesting to work on
