### ISSUE TITLE
Design the Desktop view of the Dashboard Profile Page

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#95]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=1945%3A43462

https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=1945%3A44194

**Comment by Muminat** [comment]
I did this with Michael

**Comment by MichaelAjala** [comment]
You too madam 😂

**Comment by Mimich98** [comment]
Thank you Ola
