### ISSUE TITLE
Design the Desktop view of the Dashboard Preview Page

### ISSUE THREAD

**Issue by 0laolu** [zuri-training/t_c-generator-team71#97]
https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=1640%3A42806

https://www.figma.com/file/DcoFrRWqV2bdTWdv9gM7Wk/Team-71-T%26C-and-Privacy-Policy-Gen-Project?node-id=1640%3A43531

**Comment by Muniratize** [comment]
Okayyy

**Comment by Adetunji11** [comment]
Okay
